/** Matcher span parity — 300 fuzz cases generated by the Python reference. */
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import assert from 'node:assert/strict';

import { KeywordMatcher } from '../src/matcher.js';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..', '..');
const skills = JSON.parse(readFileSync(join(here, '..', 'data', 'skills.json'), 'utf8'));
const cases = JSON.parse(
  readFileSync(join(root, 'fixtures', 'matcher_fixtures.json'), 'utf8')
);

const m = new KeywordMatcher(skills);
let spans = 0;
for (const c of cases) {
  const got = m.extract(c.text).map(([k, s, e]) => [k, s, e]);
  assert.deepEqual(got, c.spans, `mismatch on ${JSON.stringify(c.text.slice(0, 80))}`);
  spans += got.length;
}
console.log(`matcher parity ok: ${cases.length} cases, ${spans} spans`);
